posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

posts/blueprint.py
from flask import render_template, Blueprint, request, redirect, url_for

from models import Post, Tag
from .forms import PostForm
from app import db

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something wring')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))  # .all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=8)

    return render_template('posts/index.html', posts=posts, pages=pages)


# http://localhost/blog/first-post
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://localhost/blog/tag/python
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
Create new post
{% endblock %}

{% block content_title %}
New post
{% endblock %}

{% block content %}

<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form %}
        <div class="form-group">
            {{ field.label(class='control-label') }}
            {{ field(class='form-control') }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-success">Create</button>

    </form>
</div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit-post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}

<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {% for field in form %}
        <div class="form-group">
            {{ field.label(class='control-label') }}
            {{ field(class='form-control') }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-success">Edit</button>

    </form>
</div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Blueprint index page
{% endblock %}

{% block content_title %}
Posts
{% endblock %}

{% block content %}

{% for post in pages.items %}

<div class="card text-dark bg-light mb-3" style="max-width: 18rem;">
    <div class="card-header">Header</div>
    <div class="card-body">
        <div class="card-text"><a href='{{ url_for("posts.post_detail", slug=post.slug) }}'> <p align="center">{{ post.title }}</p> </a></div>
    </div>
</div>

{% endfor %}


<nav>
    <ul class="pagination">
        <li class="page-item">

            <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for page in pages.iter_pages() %}
        {% if page == pages.page %}
        <li class="page-item">
            {% endif %}
            <a class="page-link" href="./?page={{ page }}"> {{ page }} </a>
        </li>
        <li class="page-item">
            {% endfor %}

            <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
{% endblock %}

posts/templates/posts/post_detail.html
{%  extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content_title %}
<p align="center">{{ post.title }}</p>
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
           <h4><a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"><span class="badge bg-success">{{ tag.name }}</span></a></h4>
        {% endfor %}
    </div>
        {{ post.body }}

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
   Posts for '{{ tag.name }}' tag:
{% endblock %}

{% block content %}

    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}

{% endblock %}